application: nowhere-bike
version: 2
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: .*
  script: main.application
  login: required
